cafeLogProject/backend

- src/main/java/cafeLogProject/cafeLog/common/auth/AuthController.java
- src/main/java/cafeLogProject/cafeLog/common/auth/jwt/JWTFilter.java
- src/main/java/cafeLogProject/cafeLog/common/auth/jwt/JWTLoginHandler.java
- src/main/java/cafeLogProject/cafeLog/common/auth/jwt/JWTUtil.java
- src/main/java/cafeLogProject/cafeLog/common/auth/jwt/TokenExpiration.java
- src/main/java/cafeLogProject/cafeLog/common/auth/jwt/token/JWTTokenService.java
- src/main/java/cafeLogProject/cafeLog/common/config/SecurityConfig.java
토큰이 만료되었을때, /api/auth/check 에서 토큰 만료여부를 확인하지 못하고 에러메시지를 보내거나 로그인페이지로 리다이렉트하는 문제 해결.
화이트리스트에 저장한 api path 에도 JWTFilter 가 실행되는 문제 해결
> OAuth2 & JWT error clear

- src/main/java/cafeLogProject/cafeLog/api/image/service/ImageService.java
- src/main/java/cafeLogProject/cafeLog/api/review/service/ReviewService.java
- src/main/java/cafeLogProject/cafeLog/domains/image/repository/ReviewImageRepository.java
- src/main/java/cafeLogProject/cafeLog/domains/review/repository/ReviewRepositoryCustomImpl.java
> edit deleteReview api

- .gitignore
- src/main/java/cafeLogProject/cafeLog/api/image/controller/ImageController.java
- src/main/java/cafeLogProject/cafeLog/api/image/dto/RegistReviewImageResponse.java
- src/main/java/cafeLogProject/cafeLog/api/image/service/ImageService.java
- src/main/java/cafeLogProject/cafeLog/api/review/controller/ReviewController.java
- src/main/java/cafeLogProject/cafeLog/api/review/dto/ShowCafeReviewRequest.java
- src/main/java/cafeLogProject/cafeLog/api/review/dto/ShowReviewRequest.java
- src/main/java/cafeLogProject/cafeLog/api/review/dto/ShowReviewResponse.java
- src/main/java/cafeLogProject/cafeLog/api/review/dto/UpdateReviewRequest.java
- src/main/java/cafeLogProject/cafeLog/api/review/service/ReviewService.java
- src/main/java/cafeLogProject/cafeLog/domains/review/domain/Review.java
- src/main/java/cafeLogProject/cafeLog/domains/review/repository/ReviewRepositoryCustomImpl.java
- 리뷰 수정 api 수정
태그만 수정시 에러나는 오류 수정
요청시 request파라미터를 requestDto로 변경, @Valid 설정 추가
리턴시 null 대신 리뷰 데이터를 리턴하도록 변경
- 리뷰 엔티티의 주석코드 삭제
- 리뷰 이미지 등록 api 수정
리턴 형식 json형으로 변경
- 리뷰 조회 api 수정
요청시 request 파라미터를 requestDto로 변경, @Valid 설정 추가
- 리뷰 등록 api 수정
리턴시 null 대신 리뷰 데이터 리턴하도록 수정
- 리뷰삭제/리뷰이미지삭제 api 수정
성공시 http status 204 대신 200 으로 리턴하도록 변경
> edit editReview api

- src/main/java/cafeLogProject/cafeLog/api/cafe/controller/CafeController.java
- src/main/java/cafeLogProject/cafeLog/api/image/controller/ImageController.java
- src/main/java/cafeLogProject/cafeLog/api/review/controller/ReviewController.java
- src/main/java/cafeLogProject/cafeLog/domains/user/repository/UserRepository.java
- src/main/java/cafeLogProject/cafeLog/domains/user/util/NicknameGenerator.java
- src/main/resources/application.yml
- 닉네임 랜덤생성 util 제작
- path "/"를 ""로 변경
> 닉네임 랜덤생성 util 추가, 그 외 수정

- src/main/java/cafeLogProject/cafeLog/api/review/dto/RegistReviewRequest.java
- src/main/java/cafeLogProject/cafeLog/api/review/dto/ShowReviewResponse.java
- src/main/java/cafeLogProject/cafeLog/api/review/dto/UpdateReviewRequest.java
- src/main/java/cafeLogProject/cafeLog/api/review/service/ReviewService.java
- 리뷰 관련 api의 태그 request, response 방식 변경
id값으로 주고받도록 변경, 키값 "tags"에서 "tagIds"로 변경
> 태그 id로 주고받도록 변경

- src/main/java/cafeLogProject/cafeLog/api/cafe/controller/CafeController.java
- src/main/java/cafeLogProject/cafeLog/api/cafe/dto/CafeInfoRes.java
- src/main/java/cafeLogProject/cafeLog/api/cafe/service/CafeService.java
- src/main/java/cafeLogProject/cafeLog/api/user/controller/UserController.java
- src/main/java/cafeLogProject/cafeLog/api/user/dto/IsExistNicknameRes.java
- src/main/java/cafeLogProject/cafeLog/api/user/dto/UserInfoRes.java
- src/main/java/cafeLogProject/cafeLog/api/user/service/UserService.java
- src/main/java/cafeLogProject/cafeLog/domains/cafe/repository/CafeRepositoryCustom.java
- src/main/java/cafeLogProject/cafeLog/domains/cafe/repository/CafeRepositoryImpl.java
- user 프로필 조회 API (이미지 존재여부, 닉네임, 소개)
- 닉네임 중복 체크 API
> User nickname duplicate chack & get user info API

- src/main/java/cafeLogProject/cafeLog/api/review/controller/ReviewController.java
- src/main/java/cafeLogProject/cafeLog/api/review/dto/RegistReviewRequest.java
- src/main/java/cafeLogProject/cafeLog/api/review/dto/ShowReviewResponse.java
- src/main/java/cafeLogProject/cafeLog/api/review/dto/ShowUserReviewRequest.java
- src/main/java/cafeLogProject/cafeLog/api/review/dto/UpdateReviewRequest.java
- src/main/java/cafeLogProject/cafeLog/api/review/service/ReviewService.java
- src/main/java/cafeLogProject/cafeLog/common/exception/ErrorCode.java
- src/main/java/cafeLogProject/cafeLog/domains/review/repository/ReviewRepositoryCustom.java
- src/main/java/cafeLogProject/cafeLog/domains/review/repository/ReviewRepositoryCustomImpl.java
* ReviewRepositoryCustom의 search 메소드 태그 이미지 left join 후 페이징(offset/limit) 당해서 축소되는 버그 해결
* 리뷰 게시글 저장,수정,조회시 응답 json에 cafeName 추가
showReviewResponse에 cafeName 필드 추가
* 내 리뷰 조회 api 제작 완료
***해당 버전으로 모든 api 동작 가능***
> 내 리뷰 조회 api 작성, 그 외 수정

- .github/workflows/CICD-prod.yml
- CICD-prod.yml  -> Docker Image Build and Push
> Update Docker Image Build and Push In CICD-prod.yml

- README.md
- docker-compose-dev.yml
- src/main/java/cafeLogProject/cafeLog/api/draftReview/controller/DraftReviewController.java
- src/main/java/cafeLogProject/cafeLog/api/draftReview/dto/ShowUserDraftReviewResponse.java
- src/main/java/cafeLogProject/cafeLog/api/draftReview/service/DraftReviewService.java
- src/main/java/cafeLogProject/cafeLog/domains/draftReview/repository/DraftReviewRepositoryCustom.java
- src/main/java/cafeLogProject/cafeLog/domains/draftReview/repository/DraftReviewRepositoryCustomImpl.java
- 특정 cafeId의 내 임시저장 모두 조회하기 기능 추가
내 임시저장 모두 조회 api의 request에 cafeId 파라미터 추가, response에 cafeId 추가
- READ ME 내용 일부 수정
"윈도우 로컬에서 실행" 항목 부분 수정
> 내 임시저장 모두 조회 api 수정, 그 외 수정

- src/main/java/cafeLogProject/cafeLog/api/favorite/dto/ToggleFavoriteReq.java
release drafter  테 스 트 입 니 다 .
> feat: release test

- src/main/java/cafeLogProject/cafeLog/api/favorite/dto/ToggleFavoriteReq.java
> feat: release-drafter test2

- src/main/java/cafeLogProject/cafeLog/api/favorite/dto/ToggleFavoriteReq.java
refactor: release drafter 테 스 트 입 니 다 3
> refactor: release-drafter test

- .github/release-drafter-config.yml
- .github/workflows/CICD-prod.yml
- Update CICD-prod.yml to include permissions for release drafter
- refactoring release-drafter-config.yml
> refactor: release-drafter

- src/main/java/cafeLogProject/cafeLog/api/favorite/dto/ToggleFavoriteReq.java
- Release Drafter 테 스 트 입 니 다 .
> bug: release drafter test

- src/main/java/cafeLogProject/cafeLog/api/favorite/dto/ToggleFavoriteReq.java
- use "fix: " commit message and PR title.
> fix: release drafter test

- src/main/java/cafeLogProject/cafeLog/api/favorite/dto/ToggleFavoriteReq.java
- PR 생성시 라벨을 따로 선택하지 않아도 릴리즈 드래프터가 자동으로 생성해주는지 확인 테스트
> feat: 릴리즈 드래프터 기능 확인

- src/main/java/cafeLogProject/cafeLog/api/favorite/dto/ToggleFavoriteReq.java
> feat: dasdadasadsasdassdaassdads

- src/main/java/cafeLogProject/cafeLog/common/config/SecurityConfig.java
> fix: authenticationEntryPoint

- src/main/java/cafeLogProject/cafeLog/api/cafe/controller/CafeController.java
- src/main/java/cafeLogProject/cafeLog/api/cafe/dto/CafeInfoRes.java
- src/main/java/cafeLogProject/cafeLog/api/cafe/service/CafeService.java
- src/main/java/cafeLogProject/cafeLog/domains/cafe/repository/CafeRepositoryCustom.java
- src/main/java/cafeLogProject/cafeLog/domains/cafe/repository/CafeRepositoryImpl.java
- src/main/resources/application.yml
> refactor: Add isScrap in get Cafe Info

- src/main/java/cafeLogProject/cafeLog/common/config/SecurityConfig.java
- src/main/resources/application.yml
> Edit google Redirect URI

- src/main/java/cafeLogProject/cafeLog/common/auth/common/CookieUtil.java
- src/main/java/cafeLogProject/cafeLog/common/auth/jwt/JWTFilter.java
- src/main/java/cafeLogProject/cafeLog/common/auth/jwt/JWTLoginHandler.java
> refactor: Edit Cookie SameSite=None

- src/main/java/cafeLogProject/cafeLog/common/auth/jwt/JWTLoginHandler.java
- 로그인 후 response headers 에 엑세스,리프레시 토큰이 있는지 테스트
> test: response cookie test without frontendURL

- src/main/java/cafeLogProject/cafeLog/common/auth/AuthController.java
- src/main/java/cafeLogProject/cafeLog/common/auth/jwt/JWTLoginHandler.java
- /api/auth/check 에 response cookie 추가
> feat: Add respons Headers Cookie in /api/auth/check

- src/main/java/cafeLogProject/cafeLog/api/TestController.java
- src/main/java/cafeLogProject/cafeLog/domains/review/repository/ReviewRepositoryCustomImpl.java
- 프론트 에러 테스트용 api 추가 (500 Internal Server Error, 204 No Content)
- 메소드명 isLowerThenRating -> isRatingLessThanOrEqual 변경
> fix: 메소드명 변경
